### ISSUE TITLE
All plugins crashes ?

### ISSUE THREAD

**Issue by Karaulov** [BoomerangDecompiler/boomerang#162]
How to run this tool for test, in Windows 10 x64 ? I got crash at plugins

**Comment by Karaulov** [comment]
develop version

**Comment by Karaulov** [comment]
@ceeac problem in boomerang.dll file!

![blajm5u 1](https://user-images.githubusercontent.com/6445336/50502076-888a7880-0a6d-11e9-922f-08e0d1bd725e.png)

**Comment by ceeac** [comment]
This should now be fixed.
@Karaulov Please fill out the provided form the next time you make a bug report - this makes it easier to reproduce the issue.

**Comment by Karaulov** [comment]
@ceeac thanks, ok.
