### ISSUE TITLE
Error on compiling Boomerang on Mac OS 10.11 - no variant library

### ISSUE THREAD

**Issue by humanitiesclinic** [BoomerangDecompiler/boomerang#194]
**OS:** Mac OS 10.11
**Output of 'boomerang-cli --version'** [e.g. boomerang-cli v0.3.99-alpha-1701-g30f62610]

**Steps to reproduce:**
1. make
2.

**Expected/desired behaviour**
[...]

**Actual behaviour**
Scanning dependencies of target boomerang-ansic-parser_autogen
[  0%] Automatic MOC and UIC for target boomerang-ansic-parser
[  0%] Built target boomerang-ansic-parser_autogen
[  0%] [FLEX][AnsiCScanner] Building scanner with flex 2.6.4
[  0%] [BISON][AnsiCParser] Building parser with bison 3.3.2
/Users/user/AppInstalls/zDEVELOP/boomerang/src/boomerang-plugins/symbol/c/parser/AnsiCParser.y:17.1-20: warning: deprecated directive, use ‘%define api.prefix {AnsiC}’ [-Wdeprecated]
 %name-prefix "AnsiC"
 ^~~~~~~~~~~~~~~~~~~~
/Users/user/AppInstalls/zDEVELOP/boomerang/src/boomerang-plugins/symbol/c/parser/AnsiCParser.y: warning: 17 shift/reduce conflicts [-Wconflicts-sr]
/Users/user/AppInstalls/zDEVELOP/boomerang/src/boomerang-plugins/symbol/c/parser/AnsiCParser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
Scanning dependencies of target boomerang-ansic-parser
[  1%] Building CXX object src/boomerang-plugins/symbol/c/parser/CMakeFiles/boomerang-ansic-parser.dir/AnsiCParser.cpp.o
In file included from /Users/user/AppInstalls/zDEVELOP/boomerang/src/boomerang-plugins/symbol/c/parser/AnsiCParser.y:95:
/Users/user/AppInstalls/zDEVELOP/boomerang/src/boomerang/ssl/exp/Const.h:16:10: fatal error: 
      'variant' file not found
#include <variant>
         ^
1 error generated.
make[2]: *** [src/boomerang-plugins/symbol/c/parser/CMakeFiles/boomerang-ansic-parser.dir/AnsiCParser.cpp.o] Error 1
make[1]: *** [src/boomerang-plugins/symbol/c/parser/CMakeFiles/boomerang-ansic-parser.dir/all] Error 2
make: *** [all] Error 2

**Additional comments**
Have no idea how to solve this (on a Mac)

**Comment by ceeac** [comment]
I am not familiar with the build process on macOS, but [this](https://stackoverflow.com/questions/52521388/stdvariantget-does-not-compile-with-apple-llvm-10-0) suggests macOS only has proper `std::variant` support in 10.14. You can try installing official LLVM via Homebrew and use that to compile Boomerang.
