### ISSUE TITLE
error Object library target "boomerang-ssl2-parser" may not link to anything. when compiling under linux 

### ISSUE THREAD

**Issue by He1my** [BoomerangDecompiler/boomerang#205]
I was unable to compile under linux using ubuntu 18.04
had to change 
add_library(boomerang-ssl2-parser OBJECT to add_library(boomerang-ssl2-parser STATIC
and change 
add_library(boomerang-ansic-parser OBJECT TO add_library(boomerang-ansic-parser STATIC

basically undoing 0002f8380f216820dd90b4b684a33da5b28a017b for it to compile successfully

**Comment by dontpanic92** [comment]
Just came across the same error, and confirmed the fix works

**Comment by ceeac** [comment]
Thanks for your report! The build fails because CMake < 3.12 does not support linking object libraries. #207 should fix this.
