### ISSUE TITLE
Error in loader for dos4gw

### ISSUE THREAD

**Issue by zedingCZ** [BoomerangDecompiler/boomerang#239]
the operator is wrong in the condition, and it is right && place ||

`    if (!Util::testMagic(&m_LXHeader.sigLo, { 'L', 'X' }) ||
        !Util::testMagic(&m_LXHeader.sigLo, { 'L', 'E' })) {
        LOG_ERROR("Error loading file: bad LE/LX magic");
        return false;
    } 
`

**Comment by ceeac** [comment]
Fixed now. Thanks for reporting!
