### ISSUE TITLE
Build failure on Linux Mint 19.3 64-bit

### ISSUE THREAD

**Issue by akmubi** [BoomerangDecompiler/boomerang#273]
**OS: Linux Mint 19.3 (Tricia) - Cinnamon (64-bit)**

**git hash: 411041305**

Cannot build from source due to missing of "CMakeDoxyfile.tpl" or something like that

**Steps:**
1. ```sudo apt-get install git build-essential cmake qt5-default libcapstone-dev flex``` 
2. **bison** version from package manager is 3.0.4.dfsg-1build1 so in order to satisfy build requirements I decided to build from source (3.3 version in http://ftp.gnu.org/gnu/bison/)
3. ```git clone https://github.com/BoomerangDecompiler/boomerang.git```
4. ```cd boomerang```
5. ```mkdir build && cd build```
6. ```cmake ..```

**Output:**
-- Could NOT find CCache (missing: CCache_EXECUTABLE) 
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Configuring Boomerang  ...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Capstone: /usr/lib/x86_64-linux-gnu/libcapstone.so (Required is at least version "4.0.1") 
-- Found FLEX: /usr/bin/flex (found suitable version "2.6.4", minimum required is "2.6") 
-- Found BISON: /usr/bin/bison (found suitable version "3.3", minimum required is "3.3") 
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of double
-- Check size of double - done
-- Check size of float
-- Check size of float - done
-- Check size of int
-- Check size of int - done
-- Check size of int *
-- Check size of int * - done
-- Check size of long
-- Check size of long - done
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- Check size of short
-- Check size of short - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test CXX_FLAG__Wall_SUPPORTED
-- Performing Test CXX_FLAG__Wall_SUPPORTED - Success
-- Performing Test C_FLAG__Wall_SUPPORTED
-- Performing Test C_FLAG__Wall_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wextra_SUPPORTED
-- Performing Test CXX_FLAG__Wextra_SUPPORTED - Success
-- Performing Test C_FLAG__Wextra_SUPPORTED
-- Performing Test C_FLAG__Wextra_SUPPORTED - Success
-- Performing Test CXX_FLAG__Werror_SUPPORTED
-- Performing Test CXX_FLAG__Werror_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_SUPPORTED
-- Performing Test C_FLAG__Werror_SUPPORTED - Success
-- Performing Test CXX_FLAG__Werror_pedantic_SUPPORTED
-- Performing Test CXX_FLAG__Werror_pedantic_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_pedantic_SUPPORTED
-- Performing Test C_FLAG__Werror_pedantic_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wshadow_SUPPORTED
-- Performing Test CXX_FLAG__Wshadow_SUPPORTED - Success
-- Performing Test C_FLAG__Wshadow_SUPPORTED
-- Performing Test C_FLAG__Wshadow_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wformat_2_SUPPORTED
-- Performing Test CXX_FLAG__Wformat_2_SUPPORTED - Success
-- Performing Test C_FLAG__Wformat_2_SUPPORTED
-- Performing Test C_FLAG__Wformat_2_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wmissing_include_dirs_SUPPORTED
-- Performing Test CXX_FLAG__Wmissing_include_dirs_SUPPORTED - Success
-- Performing Test C_FLAG__Wmissing_include_dirs_SUPPORTED
-- Performing Test C_FLAG__Wmissing_include_dirs_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wstrict_overflow_2_SUPPORTED
-- Performing Test CXX_FLAG__Wstrict_overflow_2_SUPPORTED - Success
-- Performing Test C_FLAG__Wstrict_overflow_2_SUPPORTED
-- Performing Test C_FLAG__Wstrict_overflow_2_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wnull_dereference_SUPPORTED
-- Performing Test CXX_FLAG__Wnull_dereference_SUPPORTED - Success
-- Performing Test C_FLAG__Wnull_dereference_SUPPORTED
-- Performing Test C_FLAG__Wnull_dereference_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wduplicated_cond_SUPPORTED
-- Performing Test CXX_FLAG__Wduplicated_cond_SUPPORTED - Success
-- Performing Test C_FLAG__Wduplicated_cond_SUPPORTED
-- Performing Test C_FLAG__Wduplicated_cond_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wduplicated_branches_SUPPORTED
-- Performing Test CXX_FLAG__Wduplicated_branches_SUPPORTED - Success
-- Performing Test C_FLAG__Wduplicated_branches_SUPPORTED
-- Performing Test C_FLAG__Wduplicated_branches_SUPPORTED - Success
-- Performing Test CXX_FLAG__Walloc_zero_SUPPORTED
-- Performing Test CXX_FLAG__Walloc_zero_SUPPORTED - Success
-- Performing Test C_FLAG__Walloc_zero_SUPPORTED
-- Performing Test C_FLAG__Walloc_zero_SUPPORTED - Success
-- Performing Test CXX_FLAG__Walloca_SUPPORTED
-- Performing Test CXX_FLAG__Walloca_SUPPORTED - Success
-- Performing Test C_FLAG__Walloca_SUPPORTED
-- Performing Test C_FLAG__Walloca_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wsuggest_override_SUPPORTED
-- Performing Test CXX_FLAG__Wsuggest_override_SUPPORTED - Success
-- Performing Test C_FLAG__Wsuggest_override_SUPPORTED
-- Performing Test C_FLAG__Wsuggest_override_SUPPORTED - Failed
-- Performing Test CXX_FLAG__Wundef_SUPPORTED
-- Performing Test CXX_FLAG__Wundef_SUPPORTED - Success
-- Performing Test C_FLAG__Wundef_SUPPORTED
-- Performing Test C_FLAG__Wundef_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wunknown_pragmas_SUPPORTED
-- Performing Test CXX_FLAG__Wunknown_pragmas_SUPPORTED - Success
-- Performing Test C_FLAG__Wunknown_pragmas_SUPPORTED
-- Performing Test C_FLAG__Wunknown_pragmas_SUPPORTED - Success
-- Performing Test CXX_FLAG__fno_strict_aliasing_SUPPORTED
-- Performing Test CXX_FLAG__fno_strict_aliasing_SUPPORTED - Success
-- Performing Test C_FLAG__fno_strict_aliasing_SUPPORTED
-- Performing Test C_FLAG__fno_strict_aliasing_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wgnu_zero_variadic_macro_arguments_SUPPORTED
-- Performing Test CXX_FLAG__Wgnu_zero_variadic_macro_arguments_SUPPORTED - Failed
-- Performing Test C_FLAG__Wgnu_zero_variadic_macro_arguments_SUPPORTED
-- Performing Test C_FLAG__Wgnu_zero_variadic_macro_arguments_SUPPORTED - Failed
-- Performing Test CXX_FLAG__Werror_strict_overflow_SUPPORTED
-- Performing Test CXX_FLAG__Werror_strict_overflow_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_strict_overflow_SUPPORTED
-- Performing Test C_FLAG__Werror_strict_overflow_SUPPORTED - Success
-- Performing Test CXX_FLAG__Werror_alloca_SUPPORTED
-- Performing Test CXX_FLAG__Werror_alloca_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_alloca_SUPPORTED
-- Performing Test C_FLAG__Werror_alloca_SUPPORTED - Success
-- Performing Test CXX_FLAG__Werror_implicit_fallthrough_SUPPORTED
-- Performing Test CXX_FLAG__Werror_implicit_fallthrough_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_implicit_fallthrough_SUPPORTED
-- Performing Test C_FLAG__Werror_implicit_fallthrough_SUPPORTED - Success
-- Performing Test CXX_FLAG__Wzero_as_null_pointer_constant_SUPPORTED
-- Performing Test CXX_FLAG__Wzero_as_null_pointer_constant_SUPPORTED - Success
-- Performing Test C_FLAG__Wzero_as_null_pointer_constant_SUPPORTED
-- Performing Test C_FLAG__Wzero_as_null_pointer_constant_SUPPORTED - Failed
-- Performing Test CXX_FLAG__Werror_zero_as_null_pointer_constant_SUPPORTED
-- Performing Test CXX_FLAG__Werror_zero_as_null_pointer_constant_SUPPORTED - Success
-- Performing Test C_FLAG__Werror_zero_as_null_pointer_constant_SUPPORTED
-- Performing Test C_FLAG__Werror_zero_as_null_pointer_constant_SUPPORTED - Failed
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
error: Cannot open file /home/akmubi/Documents/boomerang/build/CMakeDoxyfile.tpl for writing
CMake Error at /usr/share/cmake-3.10/Modules/FindDoxygen.cmake:630 (message):
  Unable to generate Doxyfile template: 1
Call Stack (most recent call first):
  docs/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/akmubi/Documents/boomerang/build/CMakeFiles/CMakeOutput.log".
See also "/home/akmubi/Documents/boomerang/build/CMakeFiles/CMakeError.log".

**Additional comments:**
I just wanna read "fresh" documentation. The documentation from http://boomerang.sourceforge.net/doxy/index.html is a bit outdated, isn't it? (Generated on Tue Sep 19 21:18:14 2006)

**Comment by ceeac** [comment]
This is probably a bug in CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/19646
Does the error disappear if you run `cmake ..` for a second time?

Regarding outdated doxygen documentation - The documentation on the Sourceforge page is for the unmaintained original version of Boomerang. However, I do want to add automatically generated documentation for this version at some point in the future.

**Comment by akmubi** [comment]
Yes, ```cmake ..``` outputs the same error. I'll try to build with another cmake version.

**Comment by akmubi** [comment]
I've solved the issue. The problem was in the path that contains (i guess) non-english letters. I just moved source from /home/akmubi/Documents/boomerang to /home/akmubi/boomerang and it passed.
![image](https://user-images.githubusercontent.com/53152392/104525605-4f0c1200-5622-11eb-9f02-008683a3f494.png)
