### ISSUE TITLE
Enhance ADDRESS functionality

### ISSUE THREAD

**Issue by nemerle** [BoomerangDecompiler/boomerang#3]
ADDRESS is a class that stores both native ( Host machine ) and Target ( the machine given decompiled executable was targeted at ) addresses.
To make it a bit more usable, and to enable some additional sanity checks, it would be a good thing if it supported 'isTarget/isHost' queries.

**Comment by ceeac** [comment]
I'm closing this, since there are now separate Address (for native addresses) and HostAddress (for host addresses) classes.
