### ISSUE TITLE
Fix for a segmentation fault I found.

### ISSUE THREAD

**Issue by RobR89** [BoomerangDecompiler/boomerang#51]
In proc.cpp line 3264 there may sometimes be a segmentation fault when rename->getDef() returns null.  This needs to be tested first, as follows.

``` cpp
    if(rename->getDef() != NULL) {
      SharedType ty = rename->getDef()->getTypeFor(rename->getSubExp1());
      Exp *local = newLocal(ty, *rename);
      if(DEBUG_LIVENESS)
        LOG << "renaming " << rename << " to " << local << "\n";
      mapSymbolTo(rename, local);
    }
```

**Comment by nemerle** [comment]
Ya, I wonder why the "rename" has now def though  :frowning:

**Comment by ceeac** [comment]
This should be fixed in the current develop version, so I'm closing this. Please open a new issue if Boomerang still crashes.
