### ISSUE TITLE
program crash when i decompile .exe

### ISSUE THREAD

**Issue by Omardavinci** [BoomerangDecompiler/boomerang#53]
Boomerang crash when i try to decompile and get the source code. Why. The problem is at last because i almost get the code.

**Comment by JustGregory** [comment]
Label this with "needs more info".

**Comment by nemerle** [comment]
@JustGregory Thanks for the reminder
@Omardavinci  as the label says, we're going to need some more information about that crash:

* What kind of executable are you trying to decompile (platform/ file format etc.) ?
* Is this a freely available executable we can download and test ourselves ?

**Comment by TambourineReindeer** [comment]
This sounds similar to what I experienced myself in #44 . I still need to remember to compile with debug symbols and add more informative output.
As Nemerle mentioned above, having the executable available to test would help. And which platform is Boomerang running under itself?

**Comment by mcaldwelva** [comment]
This could be the same problem I ran into in my environment (Debian 9, gcc 6.3.0, Qt 5.7.1). Some of the full_regression tests (e.g. pentium/switch_gcc) blow up in the final stage with the following error:

terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr
Aborted

I was able to work around it by changing this line in chllcode.cpp:

```
     case opIntConst: {
-        int K = exp.access<Const>()->getInt();
+        int K = exp.toString().toInt();
         if (uns && K < 0) {

```

**Comment by ceeac** [comment]
This should be fixed in the current develop version, so I'm closing this. Please open a new issue if Boomerang still crashes.
