### ISSUE TITLE
boomerang crashes when decompiling elf sparc object file

### ISSUE THREAD

**Issue by usman77q** [BoomerangDecompiler/boomerang#55]
Hi,

boomerang crashes when decompiling elf sparc object file.
kindly advise and help.

**Comment by nemerle** [comment]
To diagnose the problem I'm going to need the file the boomerang crashes on.

Can You provide either the file, or a link where I can download it ?

**Comment by usman77q** [comment]
please give me your email i will send

**Comment by nemerle** [comment]
You could attach it to the issue/comment

Or mail it to me at nemerle5 @ gmail.com

**Comment by usman77q** [comment]
i have sent file to your email address.

**Comment by ceeac** [comment]
The crash should be fixed now. Please reopen this issue if Boomerang still crashes.
