### ISSUE TITLE
jenkins url

### ISSUE THREAD

**Issue by trivalik** [BoomerangDecompiler/boomerang#66]
The jenkins.nemerle.eu is not working.

**Comment by nemerle** [comment]
Indeed, I had to take the site down, Jenkins was being unreasonable  ( jvm was taking huge amounts of ram ). On the other hand, it was not used all that much

**Comment by ceeac** [comment]
I think we should add periodic CI job to upload the documentation to GitHub Pages some day. I'm closing this issue because this can be done using e.g. Travis CI, but I think this is a separate issue.
