### ISSUE TITLE
Fix MINGW builds

### ISSUE THREAD

**Issue by nemerle** [BoomerangDecompiler/boomerang#77]
Currently the code looks like this
```cpp
#ifdef _MSC_VER
#    include "Windows.h"
#else
#    include <dlfcn.h>
#endif
```
On mingw builds, the _MSC_VER is not set, thus we attempt to use `*nix` path.
Maybe the whole plugin stuff should be solved using Qt's support for dynamically loaded libraries ?

**Comment by ceeac** [comment]
I'm not very fond of forcing plugin writers to use Qt for writing plugins. Besides, it is much easier to just change the first line to read (untested)
```cpp
#if defined(_MSC_VER)  || defined(__MINGW32__)
```
