### ISSUE TITLE
Do not output useless gotos

### ISSUE THREAD

**Issue by rfalke** [BoomerangDecompiler/boomerang#93]
Exe: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/cfg/ia32_elf/subject.exe
Boomerang: boomerang-cli v0.3.99-alpha-1757-gd6a5867

Output (see https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/cfg/ia32_elf/by_boomerang-ng.c):

```
void basic_3_if_elseif(int param1)
{
    if (param1 == 42) {
        puts("if block");
bb0x8048631:
    }
    else {
        if (param1 == 43) {
            puts("else-if block");
        }
        else {
            goto bb0x8048631;
        }
    }
    return;
}
```

Gotos are bad in general but outputting a useless goto is even worse. See also the function basic_4_if_elseif_else.

**Comment by ceeac** [comment]
Should be fixed now that #96 is merged.
